apiVersion: v1
kind: Pod
metadata:
  name: refresh-trivydb
spec:
  containers:
  - image: appscode/natscli
    command:
      - /scripts/update-trivydb.sh
    imagePullPolicy: IfNotPresent
    name: trivydb
  restartPolicy: Never
